name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux-test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install pytest
        pip install mujoco==2.3.3
        sudo apt-get update
        sudo apt-get install libglu1-mesa-dev libgl1-mesa-dev libosmesa6-dev xvfb patchelf ffmpeg cmake swig
        wget https://github.com/google-deepmind/mujoco/releases/download/2.3.0/mujoco-2.3.0-linux-x86_64.tar.gz
        mkdir $HOME/.mujoco
        tar -xzf mujoco-2.3.0-linux-x86_64.tar.gz -C $HOME/.mujoco
        export
        pip install gymnasium
        pip install -e .[all]
        # HACK: To remove when Gymnasium 1.0.0 is released
        pip install git+https://github.com/Farama-Foundation/Gymnasium.git
    - name: Full Python tests
      env:
        LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/home/runner/.mujoco/mujoco-2.3.0/bin
      run: |
        pytest test
